# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iOSAppTime.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(610, 10, 181, 541))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.start_screenshot_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.start_screenshot_button.setObjectName("start_screenshot_button")
        self.verticalLayout.addWidget(self.start_screenshot_button)
        self.stop_screenshot_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.stop_screenshot_button.setObjectName("stop_screenshot_button")
        self.verticalLayout.addWidget(self.stop_screenshot_button)
        self.cal_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.cal_button.setObjectName("cal_button")
        self.verticalLayout.addWidget(self.cal_button)
        self.training_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.training_button.setObjectName("training_button")
        self.verticalLayout.addWidget(self.training_button)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 601, 471))
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 479, 601, 74))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.platform_label_text = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.platform_label_text.sizePolicy().hasHeightForWidth())
        self.platform_label_text.setSizePolicy(sizePolicy)
        self.platform_label_text.setAlignment(QtCore.Qt.AlignCenter)
        self.platform_label_text.setObjectName("platform_label_text")
        self.horizontalLayout.addWidget(self.platform_label_text)
        self.platform_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.platform_label.sizePolicy().hasHeightForWidth())
        self.platform_label.setSizePolicy(sizePolicy)
        self.platform_label.setText("")
        self.platform_label.setAlignment(QtCore.Qt.AlignCenter)
        self.platform_label.setObjectName("platform_label")
        self.horizontalLayout.addWidget(self.platform_label)
        self.platform_type_label_text = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.platform_type_label_text.setObjectName("platform_type_label_text")
        self.horizontalLayout.addWidget(self.platform_type_label_text)
        self.platform_type_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.platform_type_comboBox.sizePolicy().hasHeightForWidth())
        self.platform_type_comboBox.setSizePolicy(sizePolicy)
        self.platform_type_comboBox.setObjectName("platform_type_comboBox")
        self.horizontalLayout.addWidget(self.platform_type_comboBox)
        self.app_name_label_text = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.app_name_label_text.sizePolicy().hasHeightForWidth())
        self.app_name_label_text.setSizePolicy(sizePolicy)
        self.app_name_label_text.setAlignment(QtCore.Qt.AlignCenter)
        self.app_name_label_text.setObjectName("app_name_label_text")
        self.horizontalLayout.addWidget(self.app_name_label_text)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSet_ipa_file_path = QtWidgets.QAction(MainWindow)
        self.actionSet_ipa_file_path.setObjectName("actionSet_ipa_file_path")
        self.actionAdd_model_file = QtWidgets.QAction(MainWindow)
        self.actionAdd_model_file.setObjectName("actionAdd_model_file")
        self.actionSet_training_pictures = QtWidgets.QAction(MainWindow)
        self.actionSet_training_pictures.setObjectName("actionSet_training_pictures")

        self.retranslateUi(MainWindow)
        self.start_screenshot_button.clicked.connect(self.start_screenshot_button.click)
        self.stop_screenshot_button.clicked.connect(self.stop_screenshot_button.click)
        self.training_button.clicked.connect(self.training_button.click)
        self.cal_button.clicked.connect(self.cal_button.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start_screenshot_button.setText(_translate("MainWindow", "开始截图"))
        self.stop_screenshot_button.setText(_translate("MainWindow", "结束截图"))
        self.cal_button.setText(_translate("MainWindow", "计算时间"))
        self.training_button.setText(_translate("MainWindow", "一键训练"))
        self.platform_label_text.setText(_translate("MainWindow", "系统版本："))
        self.platform_type_label_text.setText(_translate("MainWindow", "平台: "))
        self.app_name_label_text.setText(_translate("MainWindow", "被测 APP :"))
        self.actionSet_ipa_file_path.setText(_translate("MainWindow", "Set ipa file path"))
        self.actionAdd_model_file.setText(_translate("MainWindow", "Add model file"))
        self.actionSet_training_pictures.setText(_translate("MainWindow", "Set training pictures"))
